kind: ConfigMap
apiVersion: v1
metadata:
  name: lightspeed-stack
data:
  lightspeed-stack.yaml: |
    name: lightspeed-core
    service:
      port: 8080
    llama_stack:
      url: http://localhost:8321
    user_data_collection:
      enabled: false
    mcp_servers:
    - name: mcp::backstage
      provider_id: model-context-protocol
      url: http://backstage-developer-hub.rhdh.svc.cluster.local/api/mcp-actions/v1
      authorization_headers:
        Authorization: "client"