apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: llama-stack-secrets
  namespace: rhdh
  labels:
    app.kubernetes.io/name: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: llama-stack-secrets
    creationPolicy: Owner
    template:
      data:
        ENABLE_VLLM: "true"
        VLLM_URL: "{{ .VLLM_URL }}"
        VLLM_API_KEY: "{{ .VLLM_API_KEY }}"
        # TODO: resolve validation issue. Relevant logs:
        # Conversation roles must alternate user/assistant/user/assistant.... Received Model Group=Llama-Guard-3-1B
        # ENABLE_VALIDATION: "true"
        # VALIDATION_PROVIDER: "vllm"
        # VALIDATION_MODEL_NAME: "Llama-Guard-3-1B"
  data:
    - secretKey: VLLM_URL
      remoteRef:
        key: secrets/litellm/credentials
        property: base_url
    - secretKey: VLLM_API_KEY
      remoteRef:
        key: secrets/litellm/credentials
        property: api_key
